AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Example template for an HTTP API that creates, updates, and deletes items in DynamoDB

Globals:
  Function:
    Timeout: 10

Resources:
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: getAllItems.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /items
            Method: GET

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: getItem.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetAnItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: GET

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: deleteItem.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        DeleteAnItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: DELETE

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: putItem.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateOrUpdateItem:
          Type: HttpApi
          Properties:
            Path: /items
            Method: PUT

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: http-crud

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/items"

  GetAllItemsFunctionArn:
    Description: "ARN of the GetAllItemsFunction"
    Value: !GetAtt GetAllItemsFunction.Arn

  GetItemFunctionArn:
    Description: "ARN of the GetItemFunction"
    Value: !GetAtt GetItemFunction.Arn

  DeleteItemFunctionArn:
    Description: "ARN of the DeleteItemFunction"
    Value: !GetAtt DeleteItemFunction.Arn

  PutItemFunctionArn:
    Description: "ARN of the PutItemFunction"
    Value: !GetAtt PutItemFunction.Arn
